run:
  name: no_postional_embeding_less_dropout_lstm_1layer_DualAttenionPooling_ResMK_CNN_BiLSTM_CNN_K357Conv_LSTM32_FC64_64_Drop10_v27
  timestamp: '2026-01-02T15:15:21.151486'
  device: cuda
training:
  batch_size: 1024
  num_train_batches: 397
  num_val_batches: 50
  dataset_name: Dataset 4 (kaggels/taruntiwarihp/phishing-site-urls)
optimizers:
  global:
    type: AdamW
    lr: 0.001
    betas: &id001
    - 0.9
    - 0.999
    weight_decay: 0.0001
  personal:
    type: AdamW
    lr: 0.001
    betas: *id001
    weight_decay: 0.0002
schedulers:
  global:
    type: ReduceLROnPlateau
    factor: 0.5
    patience: 1
  personal:
    type: ReduceLROnPlateau
    factor: 0.5
    patience: 1
